name: mobile
description: "The flutter mobile application for flutter nairobi"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^11.1.0
  flex_color_scheme: ^8.4.0
  flutter_riverpod: ^3.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  sqlite3: ^3.1.4
  riverpod_annotation: ^4.0.1
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  riverpod_generator: ^4.0.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
   - .env

  
